version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '4000:4000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
